# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2023-2026 Rodrigo Ibata
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
# This Source Code Form is "Incompatible With Secondary Licenses", as defined by the Mozilla Public License, v. 2.0.

"""Pure expression-polishing utilities shared by SR polish passes.

This module deliberately contains no data scoring and no Stage B policy.  It is
safe to reuse from both the post-hoc Pareto polisher and the in-process Stage B
accepted-step polisher.
"""

from __future__ import annotations

import math
from typing import Any, Iterable, Sequence


_SYMBOLIC_CONSTANT_TARGET_CACHE: dict[tuple[int, int], tuple[Any, ...]] = {}
_FINAL_POLISH_TARGET_CACHE: tuple[Any, ...] | None = None


def rational_snap_targets(*, max_denominator: int = 6):
    """Return simple rational/integer constants used for conservative snapping."""
    import sympy as sp

    targets: list[Any] = [
        sp.Integer(0),
        sp.Integer(1),
        sp.Integer(-1),
        sp.Integer(2),
        sp.Integer(-2),
        sp.Integer(3),
        sp.Integer(-3),
        sp.Rational(1, 2),
        sp.Rational(-1, 2),
        sp.Rational(1, 3),
        sp.Rational(-1, 3),
    ]
    for q in range(2, int(max_denominator) + 1):
        for p in range(-int(max_denominator), int(max_denominator) + 1):
            if p == 0:
                continue
            targets.append(sp.Rational(p, q))
    return dedupe_sympy_exprs(targets)


def final_polish_snap_targets():
    """Return the broader snap target list used by the post-hoc final polisher."""
    global _FINAL_POLISH_TARGET_CACHE
    import sympy as sp

    if _FINAL_POLISH_TARGET_CACHE is not None:
        return list(_FINAL_POLISH_TARGET_CACHE)

    targets = symbolic_constant_snap_targets(max_denominator=8, max_numerator=8)
    targets.extend(
        [
            sp.log(2 * sp.pi) / 2,
            -sp.log(2 * sp.pi) / 2,
        ]
    )
    _FINAL_POLISH_TARGET_CACHE = tuple(dedupe_sympy_exprs(targets))
    return list(_FINAL_POLISH_TARGET_CACHE)


def symbolic_constant_snap_targets(
    *,
    max_denominator: int = 8,
    max_numerator: int = 8,
) -> list[Any]:
    """Return compact symbolic constants generated by a small grammar.

    The grammar is intentionally simple: small rationals, a few named
    dimensionless constants, rational multiples of them, and rational multiples
    of their reciprocals.  This captures expressions such as ``1/(4*pi)``
    without hard-coding each benchmark coefficient.
    """
    import sympy as sp

    key = (int(max_denominator), int(max_numerator))
    cached = _SYMBOLIC_CONSTANT_TARGET_CACHE.get(key)
    if cached is not None:
        return list(cached)

    rationals: list[Any] = []
    for q in range(1, int(max_denominator) + 1):
        for p in range(-int(max_numerator), int(max_numerator) + 1):
            if p == 0:
                continue
            rationals.append(sp.Rational(p, q))
    rationals.extend([sp.Integer(0), sp.Integer(1), sp.Integer(-1)])
    rationals = dedupe_sympy_exprs(rationals)

    bases = [
        sp.pi,
        sp.E,
        sp.sqrt(2),
        sp.sqrt(sp.pi),
        sp.sqrt(2 * sp.pi),
        sp.pi**2,
        sp.pi**3,
    ]

    out: list[Any] = list(rationals)
    for base in bases:
        out.append(base)
        out.append(-base)
        out.append(1 / base)
        out.append(-1 / base)
        for r in rationals:
            if r == 0:
                continue
            out.append(sp.simplify(r * base))
            out.append(sp.simplify(r / base))
    result = tuple(dedupe_sympy_exprs(out))
    _SYMBOLIC_CONSTANT_TARGET_CACHE[key] = result
    return list(result)


def sympy_expr_key(expr: Any) -> str:
    """Stable-ish key for deduplicating SymPy expressions."""
    try:
        import sympy as sp

        return sp.srepr(expr)
    except Exception:
        return str(expr)


def dedupe_sympy_exprs(exprs: Iterable[Any]) -> list[Any]:
    """Deduplicate expressions while preserving first occurrence order."""
    out: list[Any] = []
    seen: set[str] = set()
    for expr in exprs:
        key = sympy_expr_key(expr)
        if key in seen:
            continue
        seen.add(key)
        out.append(expr)
    return out


def expr_depth(expr: Any) -> int:
    """Return a shallow syntactic depth proxy for a SymPy expression."""
    if not getattr(expr, "args", None):
        return 1
    return 1 + max(expr_depth(a) for a in expr.args)


def rationalize_float_exponents(
    expr: Any,
    *,
    tolerance: float = 1.0e-12,
    max_denominator: int = 12,
    rationals: Sequence[Any] | None = None,
) -> Any:
    """Replace float powers that are exactly near small rationals."""
    import sympy as sp

    if rationals is None:
        rationals = [
            sp.Rational(-3, 2),
            sp.Rational(-1, 2),
            sp.Rational(1, 2),
            sp.Rational(3, 2),
            sp.Integer(-3),
            sp.Integer(-2),
            sp.Integer(-1),
            sp.Integer(0),
            sp.Integer(1),
            sp.Integer(2),
            sp.Integer(3),
        ]

    def is_pow_with_float(e):
        return isinstance(e, sp.Pow) and isinstance(e.exp, sp.Float)

    def rewrite(e):
        val = float(e.exp)
        for q in rationals or []:
            if abs(val - float(q)) <= float(tolerance):
                return sp.Pow(e.base, q)
        q = sp.Rational(val).limit_denominator(int(max_denominator))
        if abs(val - float(q)) <= float(tolerance):
            return sp.Pow(e.base, q)
        return e

    try:
        return expr.replace(is_pow_with_float, rewrite)
    except Exception:
        return expr


def _number_distance(a: Any, b: Any) -> float:
    try:
        return abs(float(a) - float(b.evalf() if hasattr(b, "evalf") else b))
    except Exception:
        return float("inf")


def nearest_symbolic_constant(
    value: Any,
    *,
    snap_targets: Sequence[Any],
    snap_rel_tol: float,
    snap_abs_tol: float = 0.0,
) -> Any | None:
    """Return the nearest symbolic target if ``value`` is within tolerance."""
    try:
        vf = float(value)
    except Exception:
        return None
    if not math.isfinite(vf):
        return None

    best = None
    best_dist = float("inf")
    for target in snap_targets:
        try:
            tv = float(target.evalf() if hasattr(target, "evalf") else target)
        except Exception:
            continue
        dist = abs(vf - tv)
        tol = max(float(snap_abs_tol), float(snap_rel_tol) * max(1.0, abs(tv)))
        if dist <= tol and dist < best_dist:
            best = target
            best_dist = dist
    if best is None:
        return None
    try:
        if _number_distance(value, best) == 0.0:
            return None
    except Exception:
        pass
    return best


def snap_numeric_constants(
    expr: Any,
    *,
    snap_targets: Sequence[Any] | None = None,
    snap_rel_tol: float = 5.0e-4,
    snap_abs_tol: float = 0.0,
) -> Any:
    """Snap numeric atoms in an expression to compact symbolic constants."""
    import sympy as sp

    if snap_targets is None:
        snap_targets = symbolic_constant_snap_targets()

    repl: dict[Any, Any] = {}
    try:
        nums = sorted(expr.atoms(sp.Number), key=lambda n: (str(type(n)), str(n)))
    except Exception:
        return expr
    for num in nums:
        if isinstance(num, sp.Integer):
            continue
        target = nearest_symbolic_constant(
            num,
            snap_targets=snap_targets,
            snap_rel_tol=snap_rel_tol,
            snap_abs_tol=snap_abs_tol,
        )
        if target is not None:
            repl[num] = target
    if not repl:
        return expr
    try:
        # Keep this pass local to numeric atoms.  A global simplify here can
        # rewrite unrelated structure, e.g. combine logs across unitful factors.
        return sp.factor_terms(expr.xreplace(repl))
    except Exception:
        try:
            return expr.xreplace(repl)
        except Exception:
            return expr


def numeric_constant_snap_candidates(
    expr: Any,
    *,
    snap_targets: Sequence[Any] | None = None,
    snap_rel_tol: float = 5.0e-4,
    snap_abs_tol: float = 0.0,
    per_number: int = 3,
) -> list[tuple[str, Any]]:
    """Generate whole-expression candidates by snapping awkward constants."""
    import sympy as sp

    if snap_targets is None:
        snap_targets = symbolic_constant_snap_targets()

    out: list[tuple[str, Any]] = []
    try:
        all_snapped = snap_numeric_constants(
            expr,
            snap_targets=snap_targets,
            snap_rel_tol=snap_rel_tol,
            snap_abs_tol=snap_abs_tol,
        )
        if all_snapped != expr:
            out.append(("snap_symbolic_constants", all_snapped))
    except Exception:
        pass

    try:
        nums = [
            n
            for n in sorted(expr.atoms(sp.Number), key=lambda v: (str(type(v)), str(v)))
            if not isinstance(n, sp.Integer)
        ]
    except Exception:
        return out

    for num in nums:
        ranked = sorted(snap_targets, key=lambda t: (_number_distance(num, t), len(str(t)), str(t)))
        kept = 0
        for target in ranked:
            dist = _number_distance(num, target)
            if not math.isfinite(dist) or dist <= 0.0:
                continue
            try:
                tv = float(target.evalf() if hasattr(target, "evalf") else target)
            except Exception:
                continue
            tol = max(float(snap_abs_tol), float(snap_rel_tol) * max(1.0, abs(tv)))
            if dist > tol:
                continue
            try:
                out.append(
                    (
                        f"snap_symbolic_constant:{num}->{target}",
                        expr.xreplace({num: target}),
                    )
                )
            except Exception:
                continue
            kept += 1
            if kept >= int(per_number):
                break
    return out


def canonicalize_trig_phases(
    expr: Any,
    *,
    snap_rel_tol: float = 5.0e-4,
    max_pi_denominator: int = 8,
) -> Any:
    """Normalize constant phases in sin/cos calls.

    Numeric phases are first snapped to rational multiples of ``pi``.  Multiples
    of ``pi/2`` are then reduced by the sine/cosine phase group, e.g.
    ``sin(x + pi) -> -sin(x)`` and ``cos(x + pi/2) -> -sin(x)``.
    Other rational-pi phases are kept symbolically but reduced modulo ``2*pi``.
    """
    import sympy as sp

    def _snap_phase_to_pi(phase: Any) -> Any:
        if phase == 0:
            return sp.Integer(0)
        try:
            pf = float(phase.evalf() if hasattr(phase, "evalf") else phase)
        except Exception:
            return phase
        if not math.isfinite(pf):
            return phase
        qf = pf / math.pi
        q = sp.Rational(qf).limit_denominator(int(max_pi_denominator))
        if abs(qf - float(q)) <= float(snap_rel_tol) * max(1.0, abs(qf)):
            return sp.simplify(q * sp.pi)
        return phase

    def _phase_ratio(phase: Any) -> Any | None:
        try:
            ratio = sp.simplify(phase / sp.pi)
            if isinstance(ratio, sp.Rational):
                return ratio
            if ratio.is_Rational:
                return sp.Rational(ratio)
        except Exception:
            return None
        return None

    def _rewrite_call(call: Any) -> Any:
        if getattr(call, "func", None) not in (sp.sin, sp.cos):
            return call
        if len(getattr(call, "args", ())) != 1:
            return call
        arg = call.args[0]
        try:
            free = tuple(sorted(arg.free_symbols, key=lambda s: s.name))
            phase, rest = arg.as_independent(*free, as_Add=True)
        except Exception:
            return call
        phase = _snap_phase_to_pi(phase)
        ratio = _phase_ratio(phase)
        if ratio is None:
            try:
                return call.func(sp.simplify(rest + phase))
            except Exception:
                return call

        ratio = sp.Rational(ratio) % 2
        if ratio.q == 1:
            idx = int(ratio.p) % 2
            if idx == 0:
                return call.func(rest)
            return -call.func(rest)
        if ratio.q == 2:
            idx = int(2 * ratio) % 4
            if call.func == sp.sin:
                return (sp.sin(rest), sp.cos(rest), -sp.sin(rest), -sp.cos(rest))[idx]
            return (sp.cos(rest), -sp.sin(rest), -sp.cos(rest), sp.sin(rest))[idx]
        try:
            # Keep non-quadrant phases compact and symbolic, reduced modulo 2*pi.
            return call.func(sp.simplify(rest + ratio * sp.pi))
        except Exception:
            return call

    try:
        out = expr.replace(
            lambda e: getattr(e, "func", None) in (sp.sin, sp.cos)
            and len(getattr(e, "args", ())) == 1,
            _rewrite_call,
        )
        return out
    except Exception:
        return expr


def constant_code_cost(
    expr: Any,
    *,
    snap_targets: Sequence[Any],
    snap_rel_tol: float,
) -> tuple[float, int]:
    """Penalty for awkward numeric constants used by expression complexity."""
    import sympy as sp

    def _integer_cost(n: int) -> float:
        a = abs(int(n))
        if a <= 1:
            return 0.05
        if a <= 5:
            return 0.18 + 0.08 * (a - 2)
        digits = len(str(a))
        return 0.75 + 0.75 * digits + 0.15 * math.log10(a + 1.0)

    cost = 0.0
    n_long = 0
    targets = [float(t.evalf()) if hasattr(t, "evalf") else float(t) for t in snap_targets]
    for num in expr.atoms(sp.Number):
        if isinstance(num, sp.Integer):
            cost += _integer_cost(int(num))
        elif isinstance(num, sp.Rational):
            p = int(num.p)
            q = int(num.q)
            if abs(p) <= 10 and abs(q) <= 10:
                cost += 0.25
            else:
                cost += 0.75 + _integer_cost(p) + _integer_cost(q)
        elif isinstance(num, sp.Float):
            val = float(num)
            if any(abs(val - t) <= float(snap_rel_tol) * max(1.0, abs(t)) for t in targets):
                cost += 3.0
            else:
                s = f"{val:.16g}"
                digits = sum(ch.isdigit() for ch in s)
                cost += 1.6 + 0.42 * digits + max(0, digits - 12) * 0.5
                if digits > 12:
                    n_long += 1
    return float(cost), int(n_long)


__all__ = [
    "constant_code_cost",
    "canonicalize_trig_phases",
    "dedupe_sympy_exprs",
    "expr_depth",
    "final_polish_snap_targets",
    "nearest_symbolic_constant",
    "numeric_constant_snap_candidates",
    "rational_snap_targets",
    "rationalize_float_exponents",
    "snap_numeric_constants",
    "symbolic_constant_snap_targets",
    "sympy_expr_key",
]
