# SPDX-License-Identifier: MPL-2.0
"""Generalized-symmetry prototype layer for NestyNet-SR."""

from .affine_algebra import (
    AffineGeneratorView,
    AffineNormalization,
    SymmetryAlgebraSpec,
    affine_coefficient_labels,
    build_affine_determining_matrix,
    discover_affine_algebra,
)
from .algebra_certificates import (
    AffineAlgebraCertificate,
    BracketCertificate,
    affine_graph_bracket_coeffs,
    certify_affine_algebra,
    classify_affine_generator,
    unpack_affine_graph_coeffs,
)
from .algebra_casimirs import (
    AlgebraCasimirResult,
    ChargeBracketCertificate,
    StructureConstantsCertificate,
    certify_charge_brackets,
    discover_algebra_casimirs,
    extract_affine_structure_constants,
    extract_phase_structure_constants,
    normalized_positive_quadratic_casimir,
)
from .chart_bridge import (  # noqa: F401
    ChartProposal,
    ChartScanResult,
    scan_and_compile_charts,
)
from .charts import (  # noqa: F401
    IDENTITY_CHART,
    LOG_CHART,
    RECIPROCAL_CHART,
    ChartSpec,
    resolve_charts,
    snap_log_chart_algebra,
)
from .config import GeneralizedSymmetryConfig
from .carrier_bank import GSCarrier, discover_gs_carriers, rank_gs_carriers
from .generators import GeneratorSpec, discover_generator_specs, summarize_specs
from .stagea_bridge import stageA_generalized_symmetry_proposals
from .pairwise_composition import (  # noqa: F401
    compose_pairwise_monomial_proposals,
    compose_pairwise_witness_proposals,
    ray_key_from_covector,
)
from .recursive_composition import compose_recursive_coordinate_proposals  # noqa: F401
from .stagea_policy import suppress_shadowed_stagea_proposals  # noqa: F401
from .jet import JetConditionSpec, JetSeparabilitySpec, jet_separability_candidates, discover_jet_separability_specs
from .jet_bundle import JetCoordinateSpec, JetSampleTable, JetSpaceSpec, ScalarODEJetInputs
from .output_link import OutputLinkWitness, discover_output_link_separability
from .promotion import ReductionPromotionDecision, evaluate_reduction_promotion
from .prolongation import (
    ProlongationSupportStatus,
    point_prolongation_support,
    require_point_prolongation_support,
    score_affine_point_generators_from_jet_space,
    score_known_lie_point_generators_from_jet_space,
)
from .unit_torus import UnitTorusGeneratorSpec, PiInvariantSpec, enumerate_nullspace_exponents, enumerate_prefactor_exponents, unit_torus_generators_from_units_spec
from .dim_policy import DimensionalDecision, combine_dimensional_decision
from .pi_bridge import stageA_unit_torus_pi_proposals
from .de_determining import DEDeterminingResult, RecoveredDEGenerator, recover_de_generators
from .nonlinear_de_symmetry import (
    EvaluatedBracketCertificate,
    PolynomialDESymmetryCandidate,
    PolynomialDESymmetryConfig,
    PolynomialDESymmetryResult,
    pair_major_generator,
    project_generator_direction,
    recover_polynomial_de_symmetries,
)
from .de_invariant_compiler import (
    InvariantCandidateResult,
    InvariantCompilationResult,
    InvariantCompilerConfig,
    InvariantObjectiveReport,
    OrbitCoordinateResult,
    SubalgebraInvariantCompilation,
    SymbolicInvariantObjective,
    compile_orbit_coordinate,
    compile_point_invariants,
    compile_subalgebra_invariants,
    default_point_candidate_vocabulary,
    point_coordinate_ast_to_de_ast,
)
from .nonlinear_opportunity import (
    OPPORTUNITY_CASE_REGISTRY,
    OpportunityAggregateConfig,
    OpportunityAggregateResult,
    OpportunityArmMetrics,
    OpportunityAttributionConfig,
    OpportunityAttributionResult,
    OpportunityCaseSpec,
    OpportunitySampleBatch,
    aggregate_opportunity_results,
    evaluate_matched_opportunity,
    get_opportunity_case,
    list_opportunity_cases,
    sample_opportunity_case,
)
from .de_invariants import (
    DEInvariantRow,
    compile_de_invariant_library,
    de_invariant_library_report,
    de_invariant_library_rows,
)
from .quotient import (
    CoordinateSpec,
    DomainSpec,
    OutputActionSpec,
    OutputNormalFormSpec,
    ReductionPlan,
    compile_reduction_plan,
    compose_coordinate_spec_with_inputs,
    compose_reduction_plan_with_inputs,
    substitute_local_coordinate_ast,
)
from .de_upgrades import (
    PolynomialPointGenerator,
    autonomous_even_velocity_prior_rows,
    ast_discrete_signature,
    contact_jet_de_rows,
    discover_determining_equation_generators_from_jets,
    discrete_symmetry_de_rows,
    noether_variational_de_rows,
    polynomial_generator_basis,
    probe_polynomial_point_generator_basis,
    radial_reduction_de_rows,
    score_autonomous_even_velocity_prior,
    score_discrete_symmetry_terms,
    score_noether_candidate,
    symmetry_upgrade_de_term_rows,
    velocity_monomial_prior_rows,
    weighted_scaling_de_rows,
)
from .reporting import (
    build_gs_payload,
    write_gs_reports,
    reset_gs_reporter,
    configure_gs_reporter,
    record_jet_event,
    record_policy_event,
    record_unit_torus_event,
)

__all__ = [
    "AffineGeneratorView",
    "AlgebraCasimirResult",
    "AffineAlgebraCertificate",
    "AffineNormalization",
    "BracketCertificate",
    "ChargeBracketCertificate",
    "StructureConstantsCertificate",
    "SymmetryAlgebraSpec",
    "affine_coefficient_labels",
    "affine_graph_bracket_coeffs",
    "build_affine_determining_matrix",
    "certify_affine_algebra",
    "certify_charge_brackets",
    "classify_affine_generator",
    "discover_affine_algebra",
    "discover_algebra_casimirs",
    "extract_affine_structure_constants",
    "extract_phase_structure_constants",
    "normalized_positive_quadratic_casimir",
    "unpack_affine_graph_coeffs",
    "CoordinateSpec",
    "DomainSpec",
    "OutputActionSpec",
    "OutputNormalFormSpec",
    "ReductionPlan",
    "compile_reduction_plan",
    "compose_coordinate_spec_with_inputs",
    "compose_reduction_plan_with_inputs",
    "substitute_local_coordinate_ast",
    "ChartSpec",
    "IDENTITY_CHART",
    "LOG_CHART",
    "RECIPROCAL_CHART",
    "ChartProposal",
    "ChartScanResult",
    "scan_and_compile_charts",
    "resolve_charts",
    "snap_log_chart_algebra",
    "compose_pairwise_monomial_proposals",
    "compose_pairwise_witness_proposals",
    "compose_recursive_coordinate_proposals",
    "ray_key_from_covector",
    "suppress_shadowed_stagea_proposals",
    "GeneralizedSymmetryConfig",
    "GSCarrier",
    "discover_gs_carriers",
    "rank_gs_carriers",
    "GeneratorSpec",
    "discover_generator_specs",
    "summarize_specs",
    "stageA_generalized_symmetry_proposals",
    "JetConditionSpec",
    "JetSeparabilitySpec",
    "jet_separability_candidates",
    "discover_jet_separability_specs",
    "JetCoordinateSpec",
    "JetSampleTable",
    "JetSpaceSpec",
    "ScalarODEJetInputs",
    "ProlongationSupportStatus",
    "point_prolongation_support",
    "require_point_prolongation_support",
    "score_affine_point_generators_from_jet_space",
    "score_known_lie_point_generators_from_jet_space",
    "OutputLinkWitness",
    "discover_output_link_separability",
    "ReductionPromotionDecision",
    "evaluate_reduction_promotion",
    "record_jet_event",
    "record_policy_event",
    "record_unit_torus_event",
    "UnitTorusGeneratorSpec",
    "PiInvariantSpec",
    "DimensionalDecision",
    "combine_dimensional_decision",
    "enumerate_nullspace_exponents",
    "enumerate_prefactor_exponents",
    "unit_torus_generators_from_units_spec",
    "stageA_unit_torus_pi_proposals",
    "DEDeterminingResult",
    "RecoveredDEGenerator",
    "recover_de_generators",
    "EvaluatedBracketCertificate",
    "PolynomialDESymmetryCandidate",
    "PolynomialDESymmetryConfig",
    "PolynomialDESymmetryResult",
    "pair_major_generator",
    "project_generator_direction",
    "recover_polynomial_de_symmetries",
    "InvariantCandidateResult",
    "InvariantCompilationResult",
    "InvariantCompilerConfig",
    "InvariantObjectiveReport",
    "OrbitCoordinateResult",
    "SubalgebraInvariantCompilation",
    "SymbolicInvariantObjective",
    "compile_orbit_coordinate",
    "compile_point_invariants",
    "compile_subalgebra_invariants",
    "default_point_candidate_vocabulary",
    "point_coordinate_ast_to_de_ast",
    "OPPORTUNITY_CASE_REGISTRY",
    "OpportunityAggregateConfig",
    "OpportunityAggregateResult",
    "OpportunityArmMetrics",
    "OpportunityAttributionConfig",
    "OpportunityAttributionResult",
    "OpportunityCaseSpec",
    "OpportunitySampleBatch",
    "aggregate_opportunity_results",
    "evaluate_matched_opportunity",
    "get_opportunity_case",
    "list_opportunity_cases",
    "sample_opportunity_case",
    "DEInvariantRow",
    "compile_de_invariant_library",
    "de_invariant_library_report",
    "de_invariant_library_rows",
    "PolynomialPointGenerator",
    "autonomous_even_velocity_prior_rows",
    "ast_discrete_signature",
    "contact_jet_de_rows",
    "discover_determining_equation_generators_from_jets",
    "discrete_symmetry_de_rows",
    "noether_variational_de_rows",
    "polynomial_generator_basis",
    "probe_polynomial_point_generator_basis",
    "radial_reduction_de_rows",
    "score_autonomous_even_velocity_prior",
    "score_discrete_symmetry_terms",
    "score_noether_candidate",
    "symmetry_upgrade_de_term_rows",
    "velocity_monomial_prior_rows",
    "weighted_scaling_de_rows",
    "build_gs_payload",
    "write_gs_reports",
    "reset_gs_reporter",
    "configure_gs_reporter",
]
