# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2023-2026 Rodrigo Ibata
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
# This Source Code Form is "Incompatible With Secondary Licenses", as defined by the Mozilla Public License, v. 2.0.

# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
# This Source Code Form is "Incompatible With Secondary Licenses", as defined by the Mozilla Public License, v. 2.0.

# sr_core/__init__.py
from .bridges import (
    D2U,
    DU,
    Add,
    AddNode,
    Acos,
    AcosNode,
    AtomNode,
    D2Field,
    DField,
    Div,
    Field,
    FreeConst,
    Scale,
    FixedConst,
    Asin,
    AsinNode,
    Atan,
    AtanNode,
    Mul,
    MulNode,
    Node,
    U,
    Var,
    VectorFieldSpec,
    VField,
    ast_equals,
    ast_from_composite,
    ast_to_human_readable,
    build_composite_from_ast,
    build_initial_ast,
    build_product_ast,
    build_sum_ast,
    clear_vector_fields,
    clone_ast,
    clone_inputs,
    collect_nn_atoms,
    compound_input_expr,
    effective_arity,
    eval_inputs,
    extra_input_nodes,
    extra_input_var_idxs,
    get_input_exprs,
    get_vector_field_spec,
    has_nontrivial_input,
    is_pure_1d_full_compound_ast,
    is_trivial_input,
    list_vector_fields,
    make_reuse_only_nn_factory,
    make_stage_a_nn_factory,
    register_vector_field,
    replace_atom_in_ast,
    separability_proposal_to_ast,
    separability_proposal_to_ast_with_offset,
    unregister_vector_field,
    update_ast_nn_kwargs,
)
from .separability_math import (
    MultiplicativityOffset,
    build_linear_ast,
    build_mixed_compound_ast,
    build_monomial_ast,
    build_radial_r2_ast,
    build_radial_r_ast,
    check_generalized_additivity_from_derivs,
    check_linear_compound,
    check_mixed_compound,
    check_monomial_compound,
    check_monomial_compound_logderiv,
    check_separability,
    check_separability_ops,
    conv_expression,
)

__all__ = [
    "build_linear_ast",
    "build_mixed_compound_ast",
    "build_monomial_ast",
    "build_radial_r2_ast",
    "build_radial_r_ast",
    "check_generalized_additivity_from_derivs",
    "check_linear_compound",
    "check_mixed_compound",
    "check_monomial_compound",
    "check_monomial_compound_logderiv",
    "check_separability",
    "check_separability_ops",
    "conv_expression",
    "MultiplicativityOffset",
    "Node",
    "AtomNode",
    "AddNode",
    "MulNode",
    "AsinNode",
    "AcosNode",
    "AtanNode",
    "Add",
    "Div",
    "Mul",
    "Asin",
    "Acos",
    "Atan",
    "Var",
    "D2Field",
    "DField",
    "Field",
    "VectorFieldSpec",
    "VField",
    "register_vector_field",
    "unregister_vector_field",
    "clear_vector_fields",
    "get_vector_field_spec",
    "list_vector_fields",
    "FreeConst",
    "Scale",
    "FixedConst",
    "U",
    "DU",
    "D2U",
    "build_composite_from_ast",
    "ast_from_composite",
    "build_initial_ast",
    "build_product_ast",
    "build_sum_ast",
    "clone_ast",
    "update_ast_nn_kwargs",
    "ast_to_human_readable",
    "ast_equals",
    "collect_nn_atoms",
    "effective_arity",
    "compound_input_expr",
    "eval_inputs",
    "extra_input_nodes",
    "extra_input_var_idxs",
    "clone_inputs",
    "replace_atom_in_ast",
    "separability_proposal_to_ast",
    "separability_proposal_to_ast_with_offset",
    "make_stage_a_nn_factory",
    "make_reuse_only_nn_factory",
    # Unified z-space helpers
    "is_trivial_input",
    "get_input_exprs",
    "has_nontrivial_input",
    "is_pure_1d_full_compound_ast",
]
