#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2023-2026 Rodrigo Ibata
"""Sealed-test scoring of the Paper IV scalar DE benchmark.

The benchmark protocol fits each case on trajectories ic0..ic3 and uses ic4,
ic5 both to arbitrate between first-line and rescue candidates (hybrid arm)
and to report the rollout NRMSE.  Those two trajectories are therefore a
validation set.  This script scores the *final reported equation* of every
case on two further trajectories, ic6 and ic7, that no discovery or selection
step ever saw:

* the trajectories are produced by extending the protocol's seeded
  initial-condition stream from six to eight draws, so ic0..ic5 are
  regenerated byte-identically (verified here by checksum) and ic6, ic7 are
  fresh draws from the same distribution;
* the equation is rebuilt from the saved ``de_discovery.selected`` candidate
  with the same constructors and scored with the same ``validate_by_simulation``
  settings (prefix window, solver trials, blow-up guards, thresholds) the
  benchmark uses, with no refitting.

Usage::

    python3 scripts/score_paper4_sealed_test.py \
        --results-root ../NestyNet_paper4_recreation/runs/results \
        --arms scalar_stlsq scalar_hybrid

Outputs ``<results-root>/sealed_test/<arm>/summary.json`` (per-case rows with
validation and sealed-test statuses, status counts) and the regenerated
trajectories under ``<results-root>/sealed_test_data/`` (regenerable, not shipped).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
from collections import Counter
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "examples" / "feynman_de"))

PASS_NRMSE = 0.01
PARTIAL_NRMSE = 0.05
SIM_TIME_BUDGET_S = 20.0
SIM_BLOWUP_FACTOR = 100.0
SIM_BLOWUP_ABS = 1.0e6


def _md5(path: Path) -> str:
    return hashlib.md5(path.read_bytes()).hexdigest()


def _load_problems(benchmark_file: Path) -> dict:
    from problem_defs import load_problems

    probs = load_problems(str(benchmark_file))
    return probs if isinstance(probs, dict) else {str(p.id): p for p in probs}


def generate_sealed_runs(pid: str, *, benchmark_file: Path, train_dir: Path, out_dir: Path,
                         n_train: int, n_sealed: int, n_points: int, seed: int) -> dict:
    """Regenerate ``n_train + n_sealed`` trajectories; verify the first ``n_train`` match."""
    import run_benchmark as rb
    from problem_defs import default_param_values

    problem = _load_problems(benchmark_file)[pid]
    out_dir.mkdir(parents=True, exist_ok=True)
    runs, _src = rb.generate_data_multi(
        problem, default_param_values(problem), out_dir,
        n_traj=int(n_train + n_sealed), n_points=int(n_points),
        seed=int(rb._problem_seed(int(seed), pid)),
    )
    reproduced = []
    for k in range(int(n_train)):
        a = out_dir / f"de{pid}_ic{k}.csv"
        b = train_dir / f"de{pid}_ic{k}.csv"
        reproduced.append(bool(a.exists() and b.exists() and _md5(a) == _md5(b)))
    return {"runs": runs, "training_files_reproduced": reproduced}


def score_case(args: tuple) -> dict:
    pid, arms, cfg = args
    from nestynet_sr.sr_de.de_validation import candidate_to_rhs_callable, validate_by_simulation

    t0 = time.time()
    row: dict = {"id": pid, "arms": {}}
    try:
        gen = generate_sealed_runs(
            pid, benchmark_file=Path(cfg["benchmark_file"]), train_dir=Path(cfg["train_dir"]),
            out_dir=Path(cfg["data_out"]), n_train=cfg["n_train"], n_sealed=cfg["n_sealed"],
            n_points=cfg["n_points"], seed=cfg["seed"],
        )
    except Exception as exc:  # generation failure is reported, not hidden
        row["error"] = f"generation failed: {type(exc).__name__}: {exc}"
        return row
    sealed_runs = list(gen["runs"])[cfg["n_train"]:]
    row["training_files_reproduced"] = gen["training_files_reproduced"]
    row["sealed_trajectories"] = [str(r.csv_path) for r in sealed_runs]
    for arm in arms:
        case_dir = Path(cfg["results_root"]) / arm / "by_id" / pid
        jsons = sorted(case_dir.glob(f"de{pid}_ic_multi*_de.json"))
        out: dict = {}
        try:
            summ = json.loads((case_dir / "summary.json").read_text())["problems"][0]
            out["validation_status"] = summ.get("status")
            out["validation_max_nrmse"] = max(
                (float(s.get("nrmse", float("inf"))) for s in summ.get("traj_scores", [])),
                default=None,
            )
        except Exception:
            out["validation_status"] = None
        if not jsons:
            out["status"] = "MISSING"
            out["message"] = "no discovery json in case directory"
            row["arms"][arm] = out
            continue
        disc = json.loads(jsons[0].read_text())["de_discovery"]
        selected = disc.get("selected") or {}
        engine = str(selected.get("engine") or disc.get("selected_engine") or "")
        out["selected_engine"] = engine
        out["selected_kind"] = selected.get("kind")
        out["canonical_equation"] = selected.get("canonical_equation")
        try:
            order, rhs_fn = candidate_to_rhs_callable(selected, engine=engine)
            status, message, traj_scores = validate_by_simulation(
                sealed_runs, rhs_fn=rhs_fn, order=int(order),
                pass_nrmse=PASS_NRMSE, partial_nrmse=PARTIAL_NRMSE,
                traj_time_budget_s=SIM_TIME_BUDGET_S,
                blowup_factor=SIM_BLOWUP_FACTOR, blowup_abs=SIM_BLOWUP_ABS,
            )
            out.update({"status": str(status), "message": str(message), "order": int(order),
                        "traj_scores": traj_scores,
                        "sealed_max_nrmse": max((float(s.get("nrmse", float("inf")))
                                                 for s in traj_scores), default=None)})
        except Exception as exc:
            out.update({"status": "ERROR", "message": f"{type(exc).__name__}: {exc}"})
        row["arms"][arm] = out
    row["elapsed_s"] = round(time.time() - t0, 1)
    return row


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--results-root", type=Path, required=True)
    ap.add_argument("--arms", nargs="+", default=["scalar_stlsq", "scalar_hybrid"])
    ap.add_argument("--benchmark-file", type=Path, default=REPO / "data" / "feynman_de_benchmark.txt")
    ap.add_argument("--train-dir", type=Path, default=REPO / "data" / "feynman_de")
    ap.add_argument("--n-train", type=int, default=6)
    ap.add_argument("--n-sealed", type=int, default=2)
    ap.add_argument("--n-points", type=int, default=5000)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--only", nargs="*", default=None)
    ap.add_argument("--workers", type=int, default=4)
    a = ap.parse_args()

    out_root = a.results_root / "sealed_test"
    data_out = a.results_root / "sealed_test_data"  # regenerable; kept outside the shipped summaries
    data_out.mkdir(parents=True, exist_ok=True)
    ids = sorted(_load_problems(a.benchmark_file).keys())
    if a.only:
        ids = [i for i in ids if i in set(a.only)]
    cfg = {"benchmark_file": str(a.benchmark_file), "train_dir": str(a.train_dir),
           "data_out": str(data_out), "results_root": str(a.results_root),
           "n_train": a.n_train, "n_sealed": a.n_sealed, "n_points": a.n_points, "seed": a.seed}
    jobs = [(pid, list(a.arms), cfg) for pid in ids]
    with ProcessPoolExecutor(max_workers=max(1, a.workers)) as pool:
        rows = list(pool.map(score_case, jobs))

    for arm in a.arms:
        arm_rows = []
        for r in rows:
            o = dict(r.get("arms", {}).get(arm, {"status": "ERROR", "message": r.get("error")}))
            o["id"] = r["id"]
            o["training_files_reproduced"] = r.get("training_files_reproduced")
            o["sealed_trajectories"] = r.get("sealed_trajectories")
            arm_rows.append(o)
        # With --only, merge into the existing summary instead of replacing it.
        prev = out_root / arm / "summary.json"
        if a.only and prev.exists():
            kept = [q for q in json.loads(prev.read_text()).get("problems", [])
                    if str(q.get("id")) not in {str(o["id"]) for o in arm_rows}]
            arm_rows = sorted(kept + arm_rows, key=lambda q: str(q.get("id")))
        counts = Counter(str(o.get("status")) for o in arm_rows)
        val_counts = Counter(str(o.get("validation_status")) for o in arm_rows)
        changed = [(o["id"], o.get("validation_status"), o.get("status"))
                   for o in arm_rows if o.get("validation_status") != o.get("status")]
        summary = {
            "schema_version": 1,
            "arm": arm,
            "protocol": {"fit_trajectories": list(range(a.n_train - 2)),
                         "validation_trajectories": [a.n_train - 2, a.n_train - 1],
                         "sealed_test_trajectories": list(range(a.n_train, a.n_train + a.n_sealed)),
                         "n_points": a.n_points, "ic_seed": a.seed,
                         "pass_nrmse": PASS_NRMSE, "partial_nrmse": PARTIAL_NRMSE,
                         "rollout": "prefix window, 25% of span capped at 5 units, max over trajectories"},
            "status_counts": dict(counts),
            "validation_status_counts": dict(val_counts),
            "changed_cases": changed,
            "problems": arm_rows,
        }
        d = out_root / arm
        d.mkdir(parents=True, exist_ok=True)
        (d / "summary.json").write_text(json.dumps(summary, indent=1))
        print(f"{arm}: sealed {dict(counts)} | validation {dict(val_counts)} | changed: {changed}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
